"""add a column CITY with default value (...)

Revision ID: 06b3a8750b9a
Revises: a2fc7acaa0b8
Create Date: 2021-12-07 17:52:35.066490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b3a8750b9a'
down_revision = 'a2fc7acaa0b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('director', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('director', 'country')
    # ### end Alembic commands ###
