"""added a favorite movie model

Revision ID: 37125ec26d85
Revises: 8ab9aa37bd4c
Create Date: 2021-12-08 15:57:12.272724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37125ec26d85'
down_revision = '8ab9aa37bd4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_movie')
    # ### end Alembic commands ###
