"""added column favorite_genre to table user

Revision ID: 647f06a87048
Revises: 37125ec26d85
Create Date: 2021-12-08 17:54:45.385690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647f06a87048'
down_revision = '37125ec26d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('favorite_genre', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'favorite_genre')
    # ### end Alembic commands ###
