"""deleted columns surmane and country from table directors

Revision ID: 6a273c26d7d3
Revises: 8f866bddfcc6
Create Date: 2021-12-07 19:17:36.323036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a273c26d7d3'
down_revision = '8f866bddfcc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('director', 'country')
    op.drop_column('director', 'surname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('director', sa.Column('surname', sa.VARCHAR(), nullable=True))
    op.add_column('director', sa.Column('country', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
