"""jist a test

Revision ID: 8f866bddfcc6
Revises: 06b3a8750b9a
Create Date: 2021-12-07 19:12:46.402429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f866bddfcc6'
down_revision = '06b3a8750b9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
