"""add column surname to table director

Revision ID: 98c512e5190a
Revises: 1f7cc108fd02
Create Date: 2021-12-07 17:00:12.654363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c512e5190a'
down_revision = '1f7cc108fd02'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('movie')
    # op.drop_table('genre')
    # op.drop_table('r_token')
    # op.drop_table('director')
    # op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('user',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('username', sa.VARCHAR(), nullable=False),
    # sa.Column('password', sa.VARCHAR(), nullable=True),
    # sa.Column('role', sa.VARCHAR(), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('username')
    # )
    # op.create_table('director',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('name', sa.VARCHAR(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('r_token',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('token', sa.VARCHAR(), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('token')
    # )
    # op.create_table('genre',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('name', sa.VARCHAR(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('movie',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('description', sa.VARCHAR(), nullable=False),
    # sa.Column('director_id', sa.INTEGER(), nullable=False),
    # sa.Column('genre_id', sa.INTEGER(), nullable=False),
    # sa.Column('rating', sa.FLOAT(), nullable=True),
    # sa.Column('title', sa.VARCHAR(), nullable=False),
    # sa.Column('trailer', sa.VARCHAR(), nullable=True),
    # sa.Column('year', sa.INTEGER(), nullable=False),
    # sa.ForeignKeyConstraint(['director_id'], ['director.id'], ),
    # sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
