"""add a default value to column surname in table director

Revision ID: a2fc7acaa0b8
Revises: c56b76333e2a
Create Date: 2021-12-07 17:40:50.330989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2fc7acaa0b8'
down_revision = 'c56b76333e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('director', 'surname', existing_type=sa.VARCHAR(), default="...")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('director', 'surname', existing_type=sa.VARCHAR())
    # ### end Alembic commands ###
