"""added a foreign key constraint to user.favorite_genre

Revision ID: bef0270b48ce
Revises: 647f06a87048
Create Date: 2021-12-08 18:02:12.049241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef0270b48ce'
down_revision = '647f06a87048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user', 'genre', ['favorite_genre'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    # ### end Alembic commands ###
