"""add column surname to table director 2

Revision ID: c56b76333e2a
Revises: 98c512e5190a
Create Date: 2021-12-07 17:26:13.401360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c56b76333e2a'
down_revision = '98c512e5190a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('director', sa.Column('surname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('director', 'surname')
    # ### end Alembic commands ###
