name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linting:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt
    - name: Linting
      run: |
        flake8 app --max-line-length=120
    - name: Test app and enerate Report
      run: |
        coverage run --source=app -m pytest -v tests
        coverage report --show-missing
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1